name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Build & Deploy
        env:
            PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
            HOSTNAME: ${{secrets.SSH_HOST}}
            USER_NAME: ${{secrets.USER_NAME}}
      
        run: |
          echo "$PRIVATE_KEY" > private_key
          chmod 600 private_key
          
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}

          # Operations in EC2 Instance
          sudo su \
          && cd /home/ubuntu/cloud-computing-aula3 \
          && git checkout main \
          && git fetch --all \
          && git reset --hard origin/main \
          && git pull origin main \
          && sudo npm i \
          && sudo pm2 reload main.js
